/**
 * Shared types for llmtxt content workflows.
 *
 * These interfaces define the data shapes used across the llmtxt ecosystem.
 * They are intentionally decoupled from any ORM or database layer.
 */

// ── Audit Types ─────────────────────────────────────────────────

/**
 * Action type for audit logging.
 * Represents the type of operation that occurred.
 */
export type AuditAction =
  | 'auth.login'
  | 'auth.register'
  | 'auth.logout'
  | 'auth.event'
  | 'document.create'
  | 'document.update'
  | 'document.delete'
  | 'lifecycle.transition'
  | 'approval.submit'
  | 'approval.reject'
  | 'version.patch'
  | 'version.merge'
  | 'version.batch_read'
  | 'signed_url.create'
  | 'cache.clear';

/**
 * HTTP methods that cause state changes and trigger audit logging.
 */
export const STATE_CHANGING_METHODS: ReadonlySet<string> = new Set([
  'POST',
  'PUT',
  'DELETE',
  'PATCH',
]);

// ── Content Limit Constants ─────────────────────────────────────

/**
 * Hard content and resource limits enforced across the LLMtxt API.
 * These limits are immutable and apply to all users regardless of tier.
 */
export const CONTENT_LIMITS = {
  /** Maximum document content size: 10MB. */
  maxDocumentSize: 10 * 1024 * 1024,
  /** Maximum patch content size: 1MB. */
  maxPatchSize: 1 * 1024 * 1024,
  /** Maximum items in batch requests. */
  maxBatchSize: 50,
  /** Maximum version history per document. */
  maxVersionsPerDocument: 1000,
  /** Maximum documents owned per user. */
  maxDocumentsPerUser: 10_000,
  /** Maximum signed URL tokens per user (future use). */
  maxWebhooksPerUser: 20,
  /** Maximum cherry-pick merge sources per request. */
  maxMergeSources: 10,
} as const;

// ── API Versioning Constants ────────────────────────────────────

/**
 * Metadata for a specific API version.
 */
export interface ApiVersionInfo {
  version: number;
  deprecated: boolean;
  /** ISO 8601 date on which this version will stop being served. */
  sunset?: string;
}

/**
 * Registry of all supported API versions.
 * Add an entry here when a new API version ships.
 */
export const API_VERSION_REGISTRY: Readonly<Record<number, ApiVersionInfo>> = {
  1: {
    version: 1,
    deprecated: false,
  },
} as const;

/**
 * Current default API version served for unversioned requests.
 */
export const CURRENT_API_VERSION = 1;

/**
 * Latest supported API version (derived from registry).
 */
export const LATEST_API_VERSION = Math.max(...Object.keys(API_VERSION_REGISTRY).map(Number));

// ── Cross-Document Link Types ───────────────────────────────────

/**
 * Valid types for cross-document links.
 * Used when linking one document to another with semantic meaning.
 */
export const VALID_LINK_TYPES = ['references', 'depends_on', 'derived_from', 'supersedes', 'related'] as const;

/**
 * Type for a cross-document link relationship.
 */
export type LinkType = typeof VALID_LINK_TYPES[number];

// ── Collection Export Constants ─────────────────────────────────

/**
 * Separator string used when exporting multiple documents from a collection.
 * Documents are joined with double newlines for readability.
 */
export const COLLECTION_EXPORT_SEPARATOR = '\n\n';

// ── API Key Format Constants ────────────────────────────────────

/**
 * Prefix for API keys generated by the system.
 * Keys take the form: llmtxt_<43 chars base64url> = 50 chars total
 */
export const API_KEY_PREFIX = 'llmtxt_';

/**
 * Total length of a valid API key including prefix.
 * Calculated as: 7 (prefix) + 43 (base64url of 32 random bytes) = 50
 */
export const API_KEY_LENGTH = 50;

/**
 * Length of the display prefix for API keys.
 * Shows the first 8 random characters after the prefix for user identification.
 */
export const API_KEY_DISPLAY_LENGTH = 15; // "llmtxt_" (7) + first 8 random chars

// ── Document Types ──────────────────────────────────────────────

/** Supported content formats. */
export type ContentFormat = 'json' | 'text' | 'markdown';

/** Lifecycle state for collaborative documents. */
export type DocumentMode = 'draft' | 'review' | 'locked' | 'archived';

/** Metadata for a stored document. */
export interface DocumentMeta {
  id: string;
  slug: string;
  format: ContentFormat;
  contentHash: string;
  originalSize: number;
  compressedSize: number;
  tokenCount: number;
  createdAt: number;
  expiresAt: number | null;
  accessCount: number;
  lastAccessedAt: number | null;
  /** Lifecycle state (collaborative documents). */
  mode?: DocumentMode;
  /** Total number of versions. */
  versionCount?: number;
  /** Current version number. */
  currentVersion?: number;
  /** Object storage key when content lives in S3 instead of inline. */
  storageKey?: string;
}

// ── Version Types ───────────────────────────────────────────────

/** Metadata for a single document version. */
export interface VersionMeta {
  id: string;
  documentId: string;
  versionNumber: number;
  contentHash: string;
  tokenCount: number;
  createdAt: number;
  createdBy?: string;
  changelog?: string;
}

/** Summary of a version for listing (no content). */
export interface VersionSummary {
  versionNumber: number;
  tokenCount: number;
  createdAt: number;
  createdBy?: string;
  changelog?: string;
}

/** Result of comparing two versions. */
export interface VersionDiff {
  documentId: string;
  fromVersion: number;
  toVersion: number;
  addedTokens: number;
  removedTokens: number;
  addedLines: number;
  removedLines: number;
}

// ── Attachment Types (Phase 4 Bridge) ───────────────────────────

/** Reference to an llmtxt document shared in a message. */
export interface LlmtxtRef {
  slug: string;
  url: string;
  format: ContentFormat;
  tokenCount: number;
  preview: string;
}

/** Options for creating an attachment via the bridge. */
export interface AttachmentOptions {
  content: string;
  format?: ContentFormat;
  conversationId: string;
  fromAgentId: string;
  expiresInMs?: number;
}

/** Attachment fetch mode supported by the bridge/API layer. */
export type AttachmentAccessMode = 'signed_url' | 'conversation' | 'owner' | 'public';

/** Share state persisted by the API layer for an attachment. */
export type AttachmentSharingMode = 'signed_url' | 'conversation' | 'public';

/** Options for re-sharing an existing attachment. */
export interface AttachmentReshareOptions {
  expiresIn?: number;
  mode?: AttachmentSharingMode;
}

/** Options for appending a version to an existing attachment slug. */
export interface AttachmentVersionOptions {
  baseVersion?: number;
  changelog?: string;
}

// ── RBAC Types ─────────────────────────────────────────────────

/**
 * Fine-grained permission on a document.
 * Canonical definition; mirrors crates/llmtxt-core::rbac::Permission.
 */
export type Permission = 'read' | 'write' | 'delete' | 'manage' | 'approve';

/**
 * Role a user holds on a specific document.
 * Canonical definition; mirrors crates/llmtxt-core::rbac::DocumentRole.
 */
export type DocumentRole = 'owner' | 'editor' | 'viewer';

/**
 * Role a user holds within an organisation.
 * Canonical definition; mirrors crates/llmtxt-core::rbac::OrgRole.
 */
export type OrgRole = 'admin' | 'member' | 'viewer';

/**
 * Permission matrix for document roles.
 * Mirrors the ROLE_PERMISSIONS constant from the Rust core — exported here
 * so TypeScript consumers do not need to call the WASM `rolePermissions`
 * helper for static look-ups.
 */
export const ROLE_PERMISSIONS: Readonly<Record<DocumentRole, readonly Permission[]>> = {
  owner: ['read', 'write', 'delete', 'manage', 'approve'],
  editor: ['read', 'write', 'approve'],
  viewer: ['read'],
} as const;

// ── Document Event Types ────────────────────────────────────────

/**
 * Discriminant for document lifecycle events emitted by the event bus.
 *
 * Consumers should use this type when subscribing to the bus or when
 * filtering events in webhook handlers.
 */
export type DocumentEventType =
  | 'version.created'
  | 'state.changed'
  | 'approval.submitted'
  | 'approval.rejected'
  | 'document.created'
  | 'document.locked'
  | 'document.archived'
  | 'contributor.updated';

/**
 * Payload for a document lifecycle event.
 *
 * Emitted by the in-process event bus after a successful database write.
 * Consumers include WebSocket/SSE streams and webhook delivery workers.
 */
export interface DocumentEvent {
  /** Discriminant — consumers can switch on this. */
  type: DocumentEventType;
  /** Short URL slug of the affected document. */
  slug: string;
  /** Opaque document primary key. */
  documentId: string;
  /** Unix timestamp in milliseconds. */
  timestamp: number;
  /** userId or agentId that triggered the event. 'system' for auto-actions. */
  actor: string;
  /** Event-specific supplemental data. */
  data: Record<string, unknown>;
}
