-- T458: Additive-only migration — blob_attachments + net-new tables for Storage Evolution.
-- Rewritten 2026-04-17 to remove 8 duplicate CREATE TABLE statements that were
-- re-generated by drizzle-kit (api_keys, audit_logs, webhooks, organizations,
-- document_orgs, document_roles, org_members, pending_invites — all already
-- created in prior migrations).

CREATE TABLE `agent_pubkeys` (
	`id` text PRIMARY KEY,
	`agent_id` text NOT NULL UNIQUE,
	`pubkey` blob NOT NULL,
	`created_at` integer NOT NULL,
	`revoked_at` integer
);
--> statement-breakpoint
CREATE TABLE `agent_signature_nonces` (
	`nonce` text PRIMARY KEY,
	`agent_id` text NOT NULL,
	`first_seen` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `blob_attachments` (
	`id` text PRIMARY KEY,
	`doc_slug` text NOT NULL,
	`blob_name` text NOT NULL,
	`hash` text NOT NULL,
	`size` integer NOT NULL,
	`content_type` text NOT NULL,
	`uploaded_by` text NOT NULL,
	`uploaded_at` integer NOT NULL,
	`deleted_at` integer
);
--> statement-breakpoint
CREATE TABLE `document_events` (
	`id` text PRIMARY KEY,
	`document_id` text NOT NULL,
	`seq` integer NOT NULL,
	`event_type` text NOT NULL,
	`actor_id` text NOT NULL,
	`payload_json` text NOT NULL,
	`idempotency_key` text,
	`created_at` integer NOT NULL,
	`prev_hash` blob
);
--> statement-breakpoint
CREATE TABLE `section_crdt_states` (
	`document_id` text NOT NULL,
	`section_id` text NOT NULL,
	`clock` integer DEFAULT 0 NOT NULL,
	`updated_at` integer NOT NULL,
	`yrs_state` blob NOT NULL,
	CONSTRAINT `section_crdt_states_pk` PRIMARY KEY(`document_id`, `section_id`)
);
--> statement-breakpoint
CREATE TABLE `section_crdt_updates` (
	`id` text PRIMARY KEY,
	`document_id` text NOT NULL,
	`section_id` text NOT NULL,
	`update_blob` blob NOT NULL,
	`client_id` text NOT NULL,
	`seq` integer NOT NULL,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `agent_signature_nonces_agent_first_seen_idx` ON `agent_signature_nonces` (`agent_id`,`first_seen`);--> statement-breakpoint
CREATE INDEX `blob_attachments_doc_slug_idx` ON `blob_attachments` (`doc_slug`);--> statement-breakpoint
CREATE INDEX `blob_attachments_hash_idx` ON `blob_attachments` (`hash`);--> statement-breakpoint
CREATE UNIQUE INDEX `blob_attachments_active_name_idx` ON `blob_attachments` (`doc_slug`,`blob_name`) WHERE `deleted_at` IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX `document_events_doc_seq_unique` ON `document_events` (`document_id`,`seq`);--> statement-breakpoint
CREATE INDEX `section_crdt_updates_doc_section_seq_idx` ON `section_crdt_updates` (`document_id`,`section_id`,`seq`);--> statement-breakpoint
CREATE INDEX `section_crdt_updates_doc_section_created_at_idx` ON `section_crdt_updates` (`document_id`,`section_id`,`created_at`);
