/**
 * Markdown export formatter (T427.2 / T438).
 *
 * Produces a UTF-8, LF-only `.md` file with a YAML frontmatter block followed
 * by the document body. The frontmatter is generated by the canonical Rust SSoT
 * algorithm (via the `canonicalFrontmatter` bridge in `wasm.ts`).
 *
 * Output structure (§4.2 of ARCH-T427-document-export-ssot.md):
 * ```
 * ---
 * <canonical frontmatter>
 * ---
 *
 * <document body>
 * ```
 *
 * Invariants:
 * - Exactly one blank line between the closing `---` fence and the body.
 * - File ends with exactly one trailing `\n`.
 * - LF (`\n`) line endings only — no CRLF.
 * - When `opts.includeMetadata === false`, body only (no frontmatter fences).
 *
 * @see docs/specs/ARCH-T427-document-export-ssot.md §4.2
 * @module
 */

import { canonicalFrontmatter } from './canonical.js';
import type { DocumentExportState, ExportOpts } from './types.js';

export type { DocumentExportState, ExportOpts };

// ── Helpers ────────────────────────────────────────────────────

/**
 * Normalise line endings to LF and ensure exactly one trailing newline.
 *
 * Strips any trailing blank lines from `text`, then appends a single `\n`.
 */
function normaliseBody(text: string): string {
  // Normalise CRLF → LF.
  const lf = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  // Strip trailing whitespace/blank lines, then append exactly one newline.
  return lf.trimEnd() + '\n';
}

// ── Formatter ─────────────────────────────────────────────────

/**
 * Serialize a document snapshot to the Markdown export format.
 *
 * @param doc  - Self-contained document snapshot.
 * @param opts - Optional formatting flags (default: include metadata).
 * @returns UTF-8 string with LF line endings and a single trailing newline.
 */
export function formatMarkdown(doc: DocumentExportState, opts: ExportOpts = {}): string {
  const includeMetadata = opts.includeMetadata !== false;

  const body = normaliseBody(doc.content);

  if (!includeMetadata) {
    return body;
  }

  // Build canonical frontmatter via the WASM-bridge function (or TS fallback).
  const frontmatter = canonicalFrontmatter({
    title: doc.title,
    slug: doc.slug,
    version: doc.version,
    state: doc.state,
    contributors: doc.contributors,
    content_hash: doc.contentHash,
    exported_at: doc.exportedAt,
  });

  // frontmatter already ends with "---\n".
  // We add one blank line before the body per §4.2.
  return frontmatter + '\n' + body;
}
