/**
 * Swagger UI documentation route.
 *
 * Serves an interactive API documentation UI at:
 *   GET /api/docs/api          — Swagger UI HTML
 *   GET /api/openapi.json      — raw OpenAPI 3.1 spec (for tooling)
 *
 * On api.llmtxt.my the host rewrite prepends /api, so the public URLs are:
 *   https://api.llmtxt.my/docs/api
 *   https://api.llmtxt.my/openapi.json
 *
 * The spec is served as a static JSON file generated by `pnpm run openapi:gen`.
 * Both routes are exempt from authentication and rate limiting.
 *
 * Generation: run `pnpm --filter backend run openapi:gen` to regenerate the
 * spec from TSDoc `@route` annotations in `src/openapi-manifest.ts`.
 *
 * @route GET /api/docs/api
 * @route GET /api/openapi.json
 * @public
 */
import type { FastifyInstance } from 'fastify';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// openapi.json lives at apps/backend/openapi.json.
// From dist/ it's two levels up; from src/ it's one level up.
const OPENAPI_PATH = resolve(__dirname, '..', '..', 'openapi.json');

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type OpenAPIDocument = Record<string, any>;

/** Minimal valid OpenAPI 3.x stub used when the generated spec is unavailable. */
const STUB_SPEC: OpenAPIDocument = {
  openapi: '3.1.0',
  info: {
    title: 'LLMtxt API',
    version: '2026.4.6',
    description:
      'OpenAPI spec not found. Run `pnpm --filter backend run openapi:gen` to generate.',
  },
  paths: {},
};

/**
 * Register Swagger UI and OpenAPI spec serving routes.
 *
 * Reads `openapi.json` at registration time and passes it to @fastify/swagger
 * in static mode. No schema introspection of running routes is performed.
 *
 * @param app - Fastify instance to register routes on
 * @returns Promise that resolves when registration is complete
 * @public
 */
export async function docsRoutes(app: FastifyInstance): Promise<void> {
  // Load the spec — generated by `pnpm run openapi:gen`
  let specDocument: OpenAPIDocument;
  if (existsSync(OPENAPI_PATH)) {
    const raw = readFileSync(OPENAPI_PATH, 'utf-8');
    specDocument = JSON.parse(raw) as OpenAPIDocument;
  } else {
    app.log.warn(
      { openapiPath: OPENAPI_PATH },
      '[docs] openapi.json not found — serving stub spec. Run `pnpm run openapi:gen`.'
    );
    specDocument = STUB_SPEC;
  }

  // Register @fastify/swagger in static mode — reads from pre-generated spec.
  // We cast to `any` to avoid the OpenAPIV2/V3 union type mismatch: our spec
  // is OpenAPI 3.1 which @fastify/swagger types don't enumerate yet.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await app.register(fastifySwagger as any, {
    mode: 'static',
    specification: {
      document: specDocument,
    },
  });

  // Register @fastify/swagger-ui — serves interactive HTML at /docs/api
  // Public URL: https://api.llmtxt.my/docs/api (host rewrite prepends /api)
  await app.register(fastifySwaggerUi, {
    routePrefix: '/docs/api',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: true,
      displayRequestDuration: true,
      filter: true,
      syntaxHighlight: {
        activate: true,
        theme: 'agate',
      },
    },
    staticCSP: false,
    transformStaticCSP: (header) => header,
  });

  // Serve the raw spec at /openapi.json for tooling (Postman import, etc.)
  app.get(
    '/openapi.json',
    {
      config: { rateLimit: false },
    },
    async (_request, reply) => {
      return reply
        .header('Content-Type', 'application/json; charset=utf-8')
        .send(specDocument);
    }
  );
}
